languageCode = "zh-CN"
languageName = "简体中文"
weight = 1
title = "Pour l'honneur de l'esprit humain"
contentDir = 'content/zh'


[params]
  displayName = "中文"
  isoCode = "zh-CN"
  rtl = false
  description = ""
  dateFormat = "2006年1月2日"

[params.author]
  name = "Pour l'honneur de l'esprit humain"
  image = "img/avatar.png"
  headline = ""
  bio = ""
  links = [
     { link = "/" }
   ]