# -- 主菜单 --
# 主菜单显示在页面顶部的header中
# 可接受的参数包括 name, pageRef, page, url, title, weight

[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 12

[[main]]
  name = "摄影"
  pageRef = "gallery"
  weight = 13

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 15

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20


# -- 页脚菜单 --
# 页脚菜单显示在页面底部、版权信息之前